version: '3.8'

services:
  tuya-smartplug:
    build: .
    container_name: local-tuya-smartplug-dev
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./:/app:delegated
      - ./logs:/app/logs
      - ./config:/app/config:ro
    ports:
      - "8000:8000"
    environment:
      - LOGS_FOLDER=/app/logs
    networks:
      - tuya-network

networks:
  tuya-network:
    driver: bridge
