version: '3.8'

services:
  tuya-smartplug:
    build: .
    
    container_name: local-tuya-smartplug
    restart: unless-stopped
    ports:
      - "8001:8000"
    networks:
      - tuya-network

networks:
  tuya-network:
    driver: bridge