version: '3.8'

services:
  tuya-smartplug:
    build: .
    
    container_name: local-tuya-smartplug
    restart: unless-stopped
    ports:
      - "8001:8000"
    volumes:
      - /srv/dev-disk-by-uuid-1b96224b-a14e-4f97-bb09-035d598fb5df/docker/local-tuya-smartplug/local-tuya-smartplug/config:/config
    networks:
      - tuya-network

networks:
  tuya-network:
    driver: bridge